# Copyright 2026 James Casey
# SPDX-License-Identifier: Apache-2.0

[package]
name = "gof_patterns"
version = "0.1.0"
description = "Gang of Four design patterns implemented in Beamtalk"

[dependencies]
